name: Build and Deploy Zola Site

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Content Repository
      uses: actions/checkout@v2
      with:
        path: content

    - name: Checkout Theme Repository
      uses: actions/checkout@v2
      with:
        repository: thelazyone/bacter-particle-zola
        path: themes/bacter-particle

    - name: Setup Zola
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      run: |
        curl -sL "https://github.com/getzola/zola/releases/download/v0.15.3/zola-v0.15.3-x86_64-unknown-linux-gnu.tar.gz" | tar xz
        sudo mv zola /usr/local/bin/

    - name: Build Site with Zola
      run: |
        cd content
        zola build --base-url ${{ secrets.BASE_URL }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./content/public
